// src/data/readingPlans.ts
// Bible reading plans. Each plan lists its books (with chapter counts); the
// daily schedule is generated by distributing chapters as evenly as possible
// across the plan's length.

export interface PlanDay {
  day: number;
  label: string;   // e.g. "Matthew 1–3" or "Matthew 28; Mark 1"
}

export interface ReadingPlan {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  totalDays: number;
  days: PlanDay[];
}

interface BookSpec { book: string; chapters: number; }

// Distribute every chapter across `totalDays`, grouping consecutive chapters
// of the same book into a readable range label.
function buildDays(books: BookSpec[], totalDays: number): PlanDay[] {
  const chapters: { book: string; ch: number }[] = [];
  for (const b of books) {
    for (let c = 1; c <= b.chapters; c++) chapters.push({ book: b.book, ch: c });
  }

  const total = chapters.length;
  const base  = Math.floor(total / totalDays);
  const extra = total % totalDays;

  const days: PlanDay[] = [];
  let idx = 0;
  for (let d = 0; d < totalDays; d++) {
    const count = base + (d < extra ? 1 : 0);
    const slice = chapters.slice(idx, idx + count);
    idx += count;

    // Group consecutive same-book chapters into segments
    const segments: { book: string; start: number; end: number }[] = [];
    for (const c of slice) {
      const last = segments[segments.length - 1];
      if (last && last.book === c.book && c.ch === last.end + 1) {
        last.end = c.ch;
      } else {
        segments.push({ book: c.book, start: c.ch, end: c.ch });
      }
    }

    const label = segments
      .map(s => (s.start === s.end ? `${s.book} ${s.start}` : `${s.book} ${s.start}–${s.end}`))
      .join('; ');

    days.push({ day: d + 1, label: label || '—' });
  }
  return days;
}

const NEW_TESTAMENT: BookSpec[] = [
  { book: 'Matthew', chapters: 28 }, { book: 'Mark', chapters: 16 },
  { book: 'Luke', chapters: 24 },    { book: 'John', chapters: 21 },
  { book: 'Acts', chapters: 28 },    { book: 'Romans', chapters: 16 },
  { book: '1 Corinthians', chapters: 16 }, { book: '2 Corinthians', chapters: 13 },
  { book: 'Galatians', chapters: 6 }, { book: 'Ephesians', chapters: 6 },
  { book: 'Philippians', chapters: 4 }, { book: 'Colossians', chapters: 4 },
  { book: '1 Thessalonians', chapters: 5 }, { book: '2 Thessalonians', chapters: 3 },
  { book: '1 Timothy', chapters: 6 }, { book: '2 Timothy', chapters: 4 },
  { book: 'Titus', chapters: 3 }, { book: 'Philemon', chapters: 1 },
  { book: 'Hebrews', chapters: 13 }, { book: 'James', chapters: 5 },
  { book: '1 Peter', chapters: 5 }, { book: '2 Peter', chapters: 3 },
  { book: '1 John', chapters: 5 }, { book: '2 John', chapters: 1 },
  { book: '3 John', chapters: 1 }, { book: 'Jude', chapters: 1 },
  { book: 'Revelation', chapters: 22 },
];

import { SIX_MONTH_INDUCTIVE, BIBLE_COMPANION_YEAR, OSB_YEAR } from './importedPlans';

export const READING_PLANS: ReadingPlan[] = [
  {
    id: 'gospels-30',
    name: 'The Four Gospels',
    description: 'Matthew, Mark, Luke, and John in 30 days.',
    icon: '📖', color: '#7A1F2B', totalDays: 30,
    days: buildDays(
      [{ book: 'Matthew', chapters: 28 }, { book: 'Mark', chapters: 16 },
       { book: 'Luke', chapters: 24 }, { book: 'John', chapters: 21 }],
      30,
    ),
  },
  {
    id: 'john-21',
    name: 'The Gospel of John',
    description: 'One chapter a day for 21 days — ideal for a fast or a beginning.',
    icon: '🕊', color: '#1F4E8C', totalDays: 21,
    days: buildDays([{ book: 'John', chapters: 21 }], 21),
  },
  {
    id: 'psalms-30',
    name: 'The Psalms',
    description: 'Pray through all 150 Psalms in a month, five a day.',
    icon: '🎵', color: '#1D7A5C', totalDays: 30,
    days: buildDays([{ book: 'Psalm', chapters: 150 }], 30),
  },
  {
    id: 'proverbs-31',
    name: 'Proverbs in a Month',
    description: 'A chapter of wisdom each day, one for every day of the month.',
    icon: '✦', color: '#8A6516', totalDays: 31,
    days: buildDays([{ book: 'Proverbs', chapters: 31 }], 31),
  },
  {
    id: 'nt-90',
    name: 'New Testament in 90 Days',
    description: 'The whole New Testament, Matthew to Revelation, in three months.',
    icon: '☩', color: '#6A3D8F', totalDays: 90,
    days: buildDays(NEW_TESTAMENT, 90),
  },
  SIX_MONTH_INDUCTIVE,
  BIBLE_COMPANION_YEAR,
  OSB_YEAR,
];

export function getPlan(id: string): ReadingPlan | undefined {
  return READING_PLANS.find(p => p.id === id);
}
